sonar.projectKey=natthawat-b_VELORA
sonar.organization=natthawat-b

# ระบุโฟลเดอร์ที่ต้องการสแกนโค้ดทั้งหมด
sonar.sources=frontend/src, backend/src

# รวมตำแหน่งไฟล์ Coverage Report ของแต่ละส่วน
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info, backend/coverage/lcov.info
