sonar.projectKey=natthawat-b_VELORA
sonar.organization=natthawat-b

# บอกตำแหน่งไฟล์ซอร์สและไฟล์เทส
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts

# ชี้ไปที่ไฟล์ LCOV ที่ Vitest สร้างขึ้น
sonar.javascript.lcov.reportPaths=coverage/lcov.info